<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Barangay Reports</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            line-height: 1.4;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 22px;
            color: #333;
            text-transform: uppercase;
        }
        .header h3 {
            margin: 5px 0;
            font-size: 16px;
            color: #666;
        }
        .header p {
            margin: 5px 0;
            color: #777;
        }
        .filter-info {
            margin: 15px 0;
            padding: 8px;
            background: #f0f0f0;
            border-left: 4px solid #007bff;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th {
            background: #333;
            color: white;
            padding: 8px 5px;
            text-align: left;
            font-size: 10px;
            text-transform: uppercase;
        }
        td {
            padding: 6px 5px;
            border: 1px solid #ddd;
            font-size: 9px;
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 9px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
        .stats {
            margin: 20px 0;
            padding: 10px;
            background: #f5f5f5;
            border-radius: 3px;
        }
        .stats table {
            margin-top: 0;
        }
        .stats td {
            background: white;
            text-align: center;
            font-weight: bold;
        }
        .badge {
            padding: 2px 5px;
            border-radius: 2px;
            font-size: 8px;
            font-weight: bold;
        }
        .badge-success {
            background: #28a745;
            color: white;
        }
        .badge-warning {
            background: #ffc107;
            color: black;
        }
        .badge-secondary {
            background: #6c757d;
            color: white;
        }
    </style>
</head>
<body>
    <div class="header">
         @if(Auth::user()->barangay_info_id==1)
        <img style="width:120%; margin-top:-50px; margin-left:-50px;"
             src="{{ asset('public/images/logo/header_ubaldo.png') }}"
             alt="Barangay Header">
    @endif
       
    </div>

    <div class="filter-info">
         <p>Barangay Information Management System</p>
          <p>Generated By: {{Auth::user()->firstname}} {{Auth::user()->middle_initial}}. {{Auth::user()->lastname}}</p>
        <p>Generated on: {{ now()->format('F d, Y h:i A') }}</p>

        Age Category: 
        @if($ageCategory == 'all')
            <strong>All Age Groups</strong>
        @else
            <strong>{{ ucfirst($ageCategory) }}</strong> - 
            @switch($ageCategory)
                @case('infant') (0-1 year) @break
                @case('toddler') (1-3 years) @break
                @case('preschool') (3-5 years) @break
                @case('school_age') (6-12 years) @break
                @case('teenager') (13-19 years) @break
                @case('adult') (20-59 years) @break
                @case('senior') (60+ years) @break
            @endswitch
        @endif
    </div>

    <div class="stats">
        <table>
            <tr>
                <td>Total Members: {{ count($members) }}</td>
                <td>Male: {{ $members->where('sex', 'Male')->count() }}</td>
                <td>Female: {{ $members->where('sex', 'Female')->count() }}</td>
                <td>PWD: {{ $members->where('isPWD', true)->count() }}</td>
                <td>Senior: {{ $members->filter(function($m) { return $m->age >= 60; })->count() }}</td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>Age</th>
                <th>Sex</th>
                <th>Civil Status</th>
                <th>Education</th>
                <th>Employment</th>
                <th>4Ps</th>
                <th>PWD</th>
            </tr>
        </thead>
        <tbody>
            @foreach($members as $index => $member)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $member->first_name }} {{ $member->middle_name }} {{ $member->last_name }} {{ $member->extension }}</td>
                <td>{{ $member->age }}</td>
                <td>{{ $member->sex }}</td>
                <td>{{ $member->civil_status }}</td>
                <td>{{ $member->highest_education }}</td>
                <td>{{ $member->employment_status }}</td>
                <td style="text-align: center;">
                    @if($member->is_4ps_member)
                        <span class="badge badge-success">Yes</span>
                    @else
                        <span class="badge badge-secondary">No</span>
                    @endif
                </td>
                <td style="text-align: center;">
                    @if($member->isPWD)
                        <span class="badge badge-warning">{{ $member->pwd_type }}</span>
                    @else
                        <span class="badge badge-secondary">No</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is a system-generated report. Printed on {{ now()->format('F d, Y') }} v.0.0.1</p>
           <p> Developed By: Cybecore Developers Incorporation</p>
    </div>
</body>
</html>